#!/bin/bash

# setup the scripts for the transfer rl project

#################
# GENERAL

# custom python packages that should the transfered to the external devices if code is pushed
# have to be under the EU_PRJ_LOCAL_CODE_PATH directory
# if several packages are defined, then separate them with ':', for example: export EU_PRJ_CUSTOM_PACKAGES=my_package_one:my_package_two
export EU_PRJ_CUSTOM_PACKAGES=rlexp

# default script that are executed to run a repetition
export EU_PRJ_DEFAULT_RUN_REPETITION_SCRIPT="run_repetition.sh"


##################
# LOCAL

# code directory (parent directory of the transfer_rl and exputil package) at local pc
export EU_PRJ_LOCAL_CODE_PATH=/scratchlocal/creinke/data/study/perception/code

# experiment directory at local pc
export EU_PRJ_LOCAL_EXPERIMENTS_PATH=/scratchlocal/creinke/data/study/perception/experiments/sf_transfer_rl_02

# default number of parallel processes
export EU_PRJ_LOCAL_DEFAULT_NUM_PROCESSES=6

# Singularity image
export EU_PRJ_LOCAL_SINGULARITY_IMAGE=/scratchlocal/creinke/data/study/perception/singularity/sf_transfer_rl_02.sif


##################
# INRIA

# code directory (parent directory of the transfer_rl and exputil package) at Inria
export EU_PRJ_INRIA_CODE_PATH=/scratch/hydra/creinke/data/study/perception/code

# experiment directory at INRIA
export EU_PRJ_INRIA_EXPERIMENTS_PATH=/scratch/hydra/creinke/data/study/perception/experiments/sf_transfer_rl_02

# Singularity image
export EU_PRJ_INRIA_SINGULARITY_IMAGE=/scratch/hydra/creinke/data/study/perception/singularity/sf_transfer_rl_02.sif

#########
# INRIA Workstations

# default machine at inria site
export EU_PRJ_INRIA_DEFAULT_MACHINE=hydra

# default number of parallel processes
export EU_PRJ_INRIA_DEFAULT_NUM_PROCESSES=15


#########
# INRIA Cluster

# default machine at inria site
export EU_PRJ_INRIA_CLUSTER_ACCESS_MACHINE=access2-cp

# default machine at inria site
export EU_PRJ_INRIA_CLUSTER_DEFAULT_CLUSTER=perception

# default walltime: hh:mm:ss
export EU_PRJ_INRIA_CLUSTER_DEFAULT_WALLTIME=72:00:00


##################
# GRICAD Dahu Cluster

# code directory (parent directory of the transfer_rl and exputil package) at GRICAD
export EU_PRJ_GRICAD_CODE_PATH=/bettik/creinke-ext/code

# code directory (parent directory of the transfer_rl and exputil package) at GRICAD
export EU_PRJ_GRICAD_EXPERIMENTS_PATH=/bettik/creinke-ext/experiments/sf_transfer_rl_02

# default machine to run experiments
export EU_PRJ_GRICAD_DEFAULT_MACHINE=f-dahu.ciment

# default machine to transfer data
export EU_PRJ_GRICAD_DEFAULT_DATA_TRANSFER_MACHINE=creinke-ext@cargo.univ-grenoble-alpes.fr

# default number of process, i.e. cores per node
export EU_PRJ_GRICAD_DEFAULT_NUM_PROCESSES=30

# default walltime: hh:mm:ss
export EU_PRJ_GRICAD_DEFAULT_WALLTIME=48:00:00

# default project
export EU_PRJ_GRICAD_DEFAULT_PROJECT=pr-ml3ri

# default conda environment in which the code is executed
export EU_PRJ_GRICAD_DEFAULT_CONDA_ENV=sf_transfer_rl_02
