#!/usr/bin/env bash

# runs the python command in the default conda environemnt

##########################
# Parameters

CONDA_ENV=$EU_PRJ_GRICAD_DEFAULT_CONDA_ENV


##########################
# Execution

if ! command -v conda &> /dev/null
then
  #echo "Incorporate conda ..."
  source /applis/environments/conda.sh
fi

if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]; then
  #echo "Change to $CONDA_ENV conda environment ..."
  conda activate $CONDA_ENV
fi

# run python
python "$@"


