#!/bin/bash

# path to experiments on the local host
LOCAL_EXPERIMENTS_PATH=$EU_PRJ_LOCAL_EXPERIMENTS_PATH

DEFAULT_EXPERIMENTS_PATH="experiments"
DEFAULT_EXPERIMENT_PATH_PREFIX="experiment_"

# handle arguments
IS_PULL_ALL=False
EXPERIMENTS=None
while getopts ":e:m:s:a" arg; do
  case $arg in
    a) IS_PULL_ALL=True;;
    s) EXTERNAL_EXPERIMENTS_PATH=$OPTARG;;
    m) EXTERNAL_MACHINE=$OPTARG;;
    e) EXPERIMENTS=$OPTARG;;
  esac
done

if [ -z "$EXTERNAL_EXPERIMENTS_PATH" ]; then
    echo "ERROR! Need EXTERNAL_EXPERIMENTS_PATH (option -s)!"
    exit 1
fi

if [ -z "$EXTERNAL_MACHINE" ]; then
    echo "ERROR! Need EXTERNAL_MACHINE (option -m)!"
    exit 1
fi

if [ $IS_PULL_ALL == True ] && [ "$EXPERIMENTS" != None ]; then
    echo "ERROR! Can not use options -a and -e together!"
    exit 1
fi


# detect if all or only specific files should be loaded
if [ $IS_PULL_ALL == False ]; then
    # replace the path to the experiments on local host with the one at the target host
    LOCAL_EXPERIMENT_PATH=`pwd`
    EXTERNAL_EXPERIMENT_PATH=`echo $LOCAL_EXPERIMENT_PATH | sed "s+${LOCAL_EXPERIMENTS_PATH}+${EXTERNAL_EXPERIMENTS_PATH}+g"`
else
    LOCAL_EXPERIMENT_PATH=$LOCAL_EXPERIMENTS_PATH
    EXTERNAL_EXPERIMENT_PATH=$EXTERNAL_EXPERIMENTS_PATH
fi


# create list of pull requests
if [ "$EXPERIMENTS" == None ]; then
    # all data
    declare -a EXTERNAL_PATHS=("$EXTERNAL_EXPERIMENT_PATH")
    declare -a LOCAL_PATHS=("$LOCAL_EXPERIMENT_PATH")
else
    # only selected experiments
    declare -a EXTERNAL_PATHS=()
    declare -a LOCAL_PATHS=()

    if [ -f "$EXPERIMENTS" ]; then
        # read from file

        while read EXP; do
            EXTERNAL_PATHS+=("$EXTERNAL_EXPERIMENT_PATH/$DEFAULT_EXPERIMENTS_PATH/$DEFAULT_EXPERIMENT_PATH_PREFIX$EXP")
            LOCAL_PATHS+=("$LOCAL_EXPERIMENT_PATH/$DEFAULT_EXPERIMENTS_PATH/$DEFAULT_EXPERIMENT_PATH_PREFIX$EXP")
        done < "$EXPERIMENTS"

    else
        # read from comma separated list

        for EXP in $(echo $EXPERIMENTS | sed "s/,/ /g"); do
            EXTERNAL_PATHS+=("$EXTERNAL_EXPERIMENT_PATH/$DEFAULT_EXPERIMENTS_PATH/$DEFAULT_EXPERIMENT_PATH_PREFIX$EXP")
            LOCAL_PATHS+=("$LOCAL_EXPERIMENT_PATH/$DEFAULT_EXPERIMENTS_PATH/$DEFAULT_EXPERIMENT_PATH_PREFIX$EXP")
        done
    fi
fi

# execute each pull request
for i in ${!EXTERNAL_PATHS[@]}; do
    echo ${color_array[$i]}

    echo "Pull data from ${EXTERNAL_PATHS[$i]} ..."

    # exclude all "*", and then include only wanted data
    rsync -zarvm \
      --include="*/" \
      --include="*.npy" \
      --include="*.npz" \
      --include="*.dill" \
      --include="*.status" \
      --include="*.log" \
      --include="*.tblog" \
      --exclude="*" \
      "$EXTERNAL_MACHINE:${EXTERNAL_PATHS[$i]}/" "${LOCAL_PATHS[$i]}"
done
