#!/bin/bash

###############
# Parameters

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_INRIA_EXPERIMENTS_PATH
CLUSTER=$EU_PRJ_INRIA_CLUSTER_DEFAULT_CLUSTER
MACHINE=
WALLTIME=$EU_PRJ_INRIA_CLUSTER_DEFAULT_WALLTIME

###############
# Execution

ARGUMENTS=
while getopts ":m:c:w:r" arg; do
  case $arg in
    m) MACHINE=$OPTARG;;
    c) CLUSTER=$OPTARG;;
    w) WALLTIME=$OPTARG;;
    r) ARGUMENTS="$ARGUMENTS -r";;
  esac
done

# replace the path to the experiments on local host with the one at the target host
LOCAL_PATH=`pwd`
EXTERNAL_PATH=`echo $LOCAL_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`


# TODO: bring back
eu_local_generate_experiments
eu_local_inria_generate_experiments

EU_MACHINE=$MACHINE
EU_CLUSTER=$CLUSTER
export EU_MACHINE
export EU_CLUSTER

echo "Add for each repetition a job ..."
python -c "import exputils
exputils.manage.start_experiments(
  start_scripts='inria_cluster_add_job_run_repetition.sh',
  parallel=False,
  is_chdir=True,
  verbose=False,
  is_rerun=False)"

echo "Finished registering all repetitions at OAR."