#!/usr/bin/env bash

function usage {
  echo "Usage: $(basename $0) [-hut] [-i interval] [-m machine]" 2>&1
  echo "Prints the status of all experiments and repetitions that are below the current directory at INRIA."
  echo "  Options:"
  echo "   -h           Shows this message."
  echo "   -u           Only show the status of unfinished experiments to have a shorter output. Does not affect the final statistics line."
  echo "   -t           Query the status every i seconds until you force the command the quit using Ctrl+C."
  echo "   -i interval  If using the -t options, this is the interval in seconds between status updates. (Default: 5)"
  echo "   -m machine   Name of the machine at Inria which is used to query the status. (Default: $EU_PRJ_INRIA_DEFAULT_MACHINE)"
}

ssh_machine=$EU_PRJ_INRIA_DEFAULT_MACHINE

# handle arguments
arguments=
while getopts ":hum:ti:" arg; do
  case $arg in
    h) usage ; exit 1 ;;
    m) ssh_machine=${OPTARG};;
    u) arguments="$arguments -u";;
    t) arguments="$arguments -t";;
    i) arguments="$arguments -i $OPTARG";;
    ?) echo "Invalid option: -${OPTARG}."; usage ; exit 2 ;;
  esac
done

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_INRIA_EXPERIMENTS_PATH

# replace the path to the experiments on local host with the one at the target host
LOCAL_SCRIPT_PATH=`pwd`
EXTERNAL_SCRIPT_PATH=`echo $LOCAL_SCRIPT_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh $ssh_machine -t "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_SCRIPT_PATH};  eu_get_status $arguments"
