#!/bin/bash

MACHINE=$EU_PRJ_GRICAD_DEFAULT_MACHINE

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_GRICAD_EXPERIMENTS_PATH

# replace the path to the experiments on local host with the one at the target host
LOCAL_SCRIPT_PATH=`pwd`
EXTERNAL_SCRIPT_PATH=`echo $LOCAL_SCRIPT_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

## handle arguments
#while getopts ":m:" arg; do
#  case $arg in
#    m) MACHINE=$OPTARG;;
#  esac
#done

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh -tt $MACHINE "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_SCRIPT_PATH}; eu_gricad_interactive_session"