#!/usr/bin/env bash

# executes the given command in the local singularity container for the project

##################
# PARAMETERS

# directory that should be available to the singularity container
BIND_DIR_CODE=$EU_PRJ_LOCAL_CODE_PATH
BIND_DIR_EXPERIMENTS=$EU_PRJ_LOCAL_EXPERIMENTS_PATH

# location of the singularity image file
CONTAINER=$EU_PRJ_LOCAL_SINGULARITY_IMAGE

# list of custon python packages which will be added to the PYTHONPATH
CUSTOM_PYTHON_PACKAGES=("$EU_PRJ_LOCAL_CODE_PATH/exputils")
IFS=: read -raCUSTOM_PACKAGES_ARRAY<<< "$EU_PRJ_CUSTOM_PACKAGES"
for CUSTOM_PACKAGE in "${CUSTOM_PACKAGES_ARRAY[@]}"; do
  CUSTOM_PYTHON_PACKAGES+=("$EU_PRJ_LOCAL_CODE_PATH/$CUSTOM_PACKAGE")
done
#################
# EXECUTION

# grap the existing pythonpath if it exists and add the paths to the custom packages at the end
SINGULARITY_PYTHONPATH=$(singularity exec $CONTAINER env | grep PYTHONPATH)
for CUSTOM_PYTHON_PACKAGE in ${CUSTOM_PYTHON_PACKAGES[*]}; do
    SINGULARITY_PYTHONPATH=$SINGULARITY_PYTHONPATH:$CUSTOM_PYTHON_PACKAGE
done

# use the exputils library to generate the experiments and run them
SINGULARITYENV_PYTHONPATH=$SINGULARITY_PYTHONPATH singularity exec --bind $BIND_DIR_CODE,$BIND_DIR_EXPERIMENTS $CONTAINER \
  "$@"
