#!/usr/bin/env bash

function usage {
  echo "Usage: $(basename $0) [-h] [m MACHINE]" 2>&1
  echo "Prints the status of all experiments and repetitions that are below the current directory at INRIA."
  echo "  Options:"
  echo "   -h           Shows this message."
  echo "   -m MACHINE   Name of the machine at Inria which is used to query the status. (Default: $EU_PRJ_INRIA_DEFAULT_MACHINE)"
}

ssh_machine=$EU_PRJ_INRIA_DEFAULT_MACHINE

# handle arguments
while getopts ":hm:" arg; do
  case $arg in
    h) usage ; exit 1 ;;
    m) ssh_machine=${OPTARG};;
    ?) echo "Invalid option: -${OPTARG}."; usage ; exit 2 ;;
  esac
done
# get all arguments are given after the options handled by getopts
shift $(expr $OPTIND - 1 )
arguments=($@)


# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_INRIA_EXPERIMENTS_PATH

# replace the path to the experiments on local host with the one at the target host
LOCAL_SCRIPT_PATH=`pwd`
EXTERNAL_SCRIPT_PATH=`echo $LOCAL_SCRIPT_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh $ssh_machine "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_SCRIPT_PATH};  eu_get_status"
