#!/bin/bash

###############
# Parameters

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_GRICAD_EXPERIMENTS_PATH

MACHINE=$EU_PRJ_GRICAD_DEFAULT_MACHINE
NUM_PROCESSES=$EU_PRJ_GRICAD_DEFAULT_NUM_PROCESSES
WALLTIME=$EU_PRJ_GRICAD_DEFAULT_WALLTIME

###############
# Execution

ARGUMENTS=
while getopts ":m:n:w:r" arg; do
  case $arg in
    m) MACHINE=$OPTARG;;
    n) NUM_PROCESSES=$OPTARG;;
    w) WALLTIME=$OPTARG;;
    r) ARGUMENTS="$ARGUMENTS -r";;
  esac
done

# replace the path to the experiments on local host with the one at the target host
LOCAL_PATH=`pwd`
EXTERNAL_PATH=`echo $LOCAL_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh $MACHINE "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_PATH}; eu_gricad_run_repetitions -n $NUM_PROCESSES -w $WALLTIME $ARGUMENTS"
