#!/usr/bin/env bash

###############
# Parameters

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_GRICAD_EXPERIMENTS_PATH

MACHINE=$EU_PRJ_GRICAD_DEFAULT_MACHINE

###############
# Execution

# replace the path to the experiments on local host with the one at the target host
LOCAL_PATH=`pwd`
EXTERNAL_PATH=`echo $LOCAL_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh $MACHINE "source eu_activate $EU_ACTIVE_PRJ; cd ${EXTERNAL_PATH}; eu_get_status"
