#!/usr/bin/env bash

function usage {
  echo "Usage: $(basename $0) [-ht] [-i interval] [-m machine]" 2>&1
  echo "Connects to Inria via ssh. Connects to the same experiment folder you are currently in."
  echo "  Options:"
  echo "   -h           Shows this message."
  echo "   -m machine   Name of the machine at you want to connect with. (Default: $EU_PRJ_INRIA_DEFAULT_MACHINE)"
}

ssh_machine=$EU_PRJ_INRIA_DEFAULT_MACHINE

# handle arguments
arguments=
while getopts ":hm:ti:" arg; do
  case $arg in
    h) usage ; exit 1 ;;
    m) ssh_machine=${OPTARG};;
    ?) echo "Invalid option: -${OPTARG}."; usage ; exit 2 ;;
  esac
done

# path to experiments on the local host
LOCAL_EXPERIMENTS_DIR=$EU_PRJ_LOCAL_EXPERIMENTS_PATH
# path to the experiments directory on the target host
EXTERNAL_EXPERIMENTS_DIR=$EU_PRJ_INRIA_EXPERIMENTS_PATH

# replace the path to the experiments on local host with the one at the target host
LOCAL_SCRIPT_PATH=`pwd`
EXTERNAL_SCRIPT_PATH=`echo $LOCAL_SCRIPT_PATH | sed "s+${LOCAL_EXPERIMENTS_DIR}+${EXTERNAL_EXPERIMENTS_DIR}+g"`

# got to the current experiment directory on the target host and start the "run_experiments.sh" script
ssh $ssh_machine -t "cd ${EXTERNAL_SCRIPT_PATH}; bash -i <<< 'source eu_activate $EU_ACTIVE_PRJ; exec </dev/tty'"